/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Etiqueta;

import ArquivoTexto.ReadTexto;
import ArquivoTexto.SalvarArquivoTexto;
import modozpl.LogoNew;
import modozpl.LogoSincron5;
import java.io.IOException;
import java.util.Arrays;
import java.util.Iterator;
import java.util.NoSuchElementException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author vmbrito
 */
public class TesteMarca extends javax.swing.JFrame {

    /**
     * Creates new form TesteMarca
     */
    public TesteMarca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tf_pw = new javax.swing.JTextField();
        tf_ll = new javax.swing.JTextField();
        tf_inicio = new javax.swing.JTextField();
        tf_quantCol = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_linha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_espCol = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_linhasImpressas = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 240, -1));
        getContentPane().add(tf_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 170, -1));
        getContentPane().add(tf_ll, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 160, -1));

        tf_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_inicioActionPerformed(evt);
            }
        });
        getContentPane().add(tf_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 170, -1));

        tf_quantCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_quantColActionPerformed(evt);
            }
        });
        getContentPane().add(tf_quantCol, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 110, -1));

        jLabel1.setText("PW");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel2.setText("LL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jLabel3.setText("Inicio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel4.setText("Linha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));
        getContentPane().add(tf_linha, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 160, -1));

        jLabel5.setText("Quantidade de colunas por impressão");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel6.setText("Quantidade de linhas a ser impressa");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));
        getContentPane().add(tf_espCol, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 110, -1));

        jLabel7.setText("Espacamento entres as colunas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 30));
        getContentPane().add(tf_linhasImpressas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 110, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Logo 5 mm", "Logo 10 mm", "Logo 15 mm", "Logo 20 mm", "Logo 25 mm" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 350, 40));

        jButton2.setText("Salvar Parametros");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 230, -1));

        setSize(new java.awt.Dimension(1009, 682));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       LogoNew log = new LogoNew();
       
       LogoSincron5 marca = new LogoSincron5();
       
     
       
        String pw = tf_pw.getText();
        String LL = tf_ll.getText();
        String linha1 = tf_inicio.getText();
        String linha2 = tf_linha.getText();
        int coluna = 0;
        int quantLinha = 0;
        int valorColuna = 0;
        if (tf_quantCol.getText() != null) {
            coluna = Integer.parseInt(tf_quantCol.getText());
        }

        if (tf_linhasImpressas.getText() != null) {
            quantLinha = Integer.parseInt(tf_linhasImpressas.getText());
        }

        if (tf_espCol.getText() != null) {
            valorColuna = Integer.parseInt(tf_espCol.getText());
        }

            String marc = null;

        switch (jComboBox1.getSelectedIndex()) {

            case 0:
                marc = marca.gerarMarca(log.getLogoSincron5(), pw, LL, linha1, linha2, coluna, quantLinha, valorColuna);
                break;
            case 1:
                marc = marca.gerarMarca(log.getLogoSincron10(), pw, LL, linha1, linha2, coluna, quantLinha, valorColuna);
                break;
            case 2:
                marc = marca.gerarMarca(log.getLogoSincron15(), pw, LL, linha1, linha2, coluna, quantLinha, valorColuna);
                break;

            case 3:
                marc = marca.gerarMarca(log.getLogoSincron20(), pw, LL, linha1, linha2, coluna, quantLinha, valorColuna);
                break;
            case 4:
                marc = marca.gerarMarca(log.getLogoSincron25(), pw, LL, linha1, linha2, coluna, quantLinha, valorColuna);
                break;

        }
             

       
      
        System.out.println(marc);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_inicioActionPerformed

    private void tf_quantColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_quantColActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_quantColActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       
         
        try {
            Iterator<String> parametros = (Iterator<String>) Arrays.stream(ReadTexto.lerArquivo(jComboBox1.getSelectedItem().toString()).split(","))
                    .map(e -> e.trim()).iterator();

            try{
            tf_pw.setText(parametros.next());
            tf_ll.setText(parametros.next());
            tf_inicio.setText(parametros.next());
            tf_linha.setText(parametros.next());
            tf_quantCol.setText(parametros.next());
            tf_linhasImpressas.setText(parametros.next());
            tf_espCol.setText(parametros.next());
           
            } catch(NoSuchElementException e){
                     
                     }

        } catch (IOException ex) {
            Logger.getLogger(TesteMarca.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
              
         StringBuilder sb = new StringBuilder();
         
         sb.append(tf_pw.getText());
         sb.append(",");
         sb.append(tf_ll.getText());
         sb.append(",");
         sb.append(tf_inicio.getText());
         sb.append(",");
         sb.append(tf_linha.getText());
         sb.append(",");
         sb.append(tf_quantCol.getText());
         sb.append(",");
         sb.append(tf_linhasImpressas.getText());
         sb.append(",");
         sb.append(tf_espCol.getText()); 
         
        try {
            SalvarArquivoTexto.salvar(sb.toString(),jComboBox1.getSelectedItem().toString());
        } catch (IOException ex) {
            Logger.getLogger(TesteMarca.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesteMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesteMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesteMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesteMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesteMarca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tf_espCol;
    private javax.swing.JTextField tf_inicio;
    private javax.swing.JTextField tf_linha;
    private javax.swing.JTextField tf_linhasImpressas;
    private javax.swing.JTextField tf_ll;
    private javax.swing.JTextField tf_pw;
    private javax.swing.JTextField tf_quantCol;
    // End of variables declaration//GEN-END:variables
}
