/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Config;

import CutRev.Marca1;

/**
 *
 * @author V103760
 */
public class Configuracao extends javax.swing.JFrame {

      Marca1 mar = new Marca1();
    public Configuracao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_espacamentoLinha = new javax.swing.JTextField();
        tf_espacamentoEsquerdo = new javax.swing.JTextField();
        tf_colunaLogo = new javax.swing.JTextField();
        tf_AlturaLogo = new javax.swing.JTextField();
        tf_alturaText1 = new javax.swing.JTextField();
        tf_TamanhoText1 = new javax.swing.JTextField();
        TF_text1 = new javax.swing.JTextField();
        tf_colunaText1 = new javax.swing.JTextField();
        tf_doisDColuna2 = new javax.swing.JTextField();
        tf_doisDColuna1 = new javax.swing.JTextField();
        tf_doisDaltura2 = new javax.swing.JTextField();
        tf_colunaBrazil = new javax.swing.JTextField();
        tf_colunaMadeIn = new javax.swing.JTextField();
        tf_doisDaltura1 = new javax.swing.JTextField();
        tf_colunaDescricao = new javax.swing.JTextField();
        tf_alturadescricao = new javax.swing.JTextField();
        tf_LarguraDescricao = new javax.swing.JTextField();
        tf_TamanhoDescricao = new javax.swing.JTextField();
        TF_text2 = new javax.swing.JTextField();
        TF_text3 = new javax.swing.JTextField();
        TF_text4 = new javax.swing.JTextField();
        TF_text5 = new javax.swing.JTextField();
        TF_text6 = new javax.swing.JTextField();
        tf_colunaText2 = new javax.swing.JTextField();
        tf_colunaText3 = new javax.swing.JTextField();
        tf_colunaText4 = new javax.swing.JTextField();
        tf_colunaText5 = new javax.swing.JTextField();
        tf_colunaText6 = new javax.swing.JTextField();
        tf_alturaText2 = new javax.swing.JTextField();
        tf_alturaText3 = new javax.swing.JTextField();
        tf_alturaText4 = new javax.swing.JTextField();
        tf_alturaText5 = new javax.swing.JTextField();
        tf_alturaText6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_LarguraText1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_LarguraText2 = new javax.swing.JTextField();
        tf_LarguraText3 = new javax.swing.JTextField();
        tf_LarguraText4 = new javax.swing.JTextField();
        tf_LarguraText5 = new javax.swing.JTextField();
        tf_LarguraText6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_TamanhoText2 = new javax.swing.JTextField();
        tf_TamanhoText3 = new javax.swing.JTextField();
        tf_TamanhoText4 = new javax.swing.JTextField();
        tf_TamanhoText5 = new javax.swing.JTextField();
        tf_TamanhoText6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        tf_LarguraMadeIn = new javax.swing.JTextField();
        tf_LaguraBrasil = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        tf_TamMadeIn = new javax.swing.JTextField();
        tf_TamBrasil = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        tf_codigoBarrasColuna = new javax.swing.JTextField();
        tf_codigoBarrasAltura = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_espacamentoLinha.setBackground(new java.awt.Color(204, 204, 204));
        tf_espacamentoLinha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_espacamentoLinha.setBorder(null);
        getContentPane().add(tf_espacamentoLinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 140, 30));

        tf_espacamentoEsquerdo.setBackground(new java.awt.Color(204, 204, 204));
        tf_espacamentoEsquerdo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tf_espacamentoEsquerdo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_espacamentoEsquerdo.setBorder(null);
        getContentPane().add(tf_espacamentoEsquerdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 150, 30));

        tf_colunaLogo.setBackground(new java.awt.Color(204, 204, 204));
        tf_colunaLogo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tf_colunaLogo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_colunaLogo.setBorder(null);
        getContentPane().add(tf_colunaLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 110, 30));

        tf_AlturaLogo.setBackground(new java.awt.Color(204, 204, 204));
        tf_AlturaLogo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_AlturaLogo.setBorder(null);
        getContentPane().add(tf_AlturaLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 110, 30));

        tf_alturaText1.setBackground(new java.awt.Color(204, 204, 204));
        tf_alturaText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_alturaText1.setBorder(null);
        tf_alturaText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_alturaText1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_alturaText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 60, 30));

        tf_TamanhoText1.setBackground(new java.awt.Color(204, 204, 204));
        tf_TamanhoText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_TamanhoText1.setBorder(null);
        getContentPane().add(tf_TamanhoText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 260, 60, 30));

        TF_text1.setBorder(null);
        TF_text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_text1ActionPerformed(evt);
            }
        });
        getContentPane().add(TF_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 255, 660, 25));

        tf_colunaText1.setBackground(new java.awt.Color(204, 204, 204));
        tf_colunaText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_colunaText1.setBorder(null);
        tf_colunaText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_colunaText1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_colunaText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 60, 30));

        tf_doisDColuna2.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(tf_doisDColuna2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 60, -1));

        tf_doisDColuna1.setBackground(new java.awt.Color(204, 204, 204));
        tf_doisDColuna1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_doisDColuna1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_doisDColuna1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_doisDColuna1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 60, -1));

        tf_doisDaltura2.setBackground(new java.awt.Color(204, 204, 204));
        tf_doisDaltura2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_doisDaltura2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_doisDaltura2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_doisDaltura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 770, 90, -1));

        tf_colunaBrazil.setBackground(new java.awt.Color(204, 204, 204));
        tf_colunaBrazil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_colunaBrazil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_colunaBrazilActionPerformed(evt);
            }
        });
        getContentPane().add(tf_colunaBrazil, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 740, 90, -1));

        tf_colunaMadeIn.setBackground(new java.awt.Color(204, 204, 204));
        tf_colunaMadeIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_colunaMadeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_colunaMadeInActionPerformed(evt);
            }
        });
        getContentPane().add(tf_colunaMadeIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 690, 100, -1));

        tf_doisDaltura1.setBackground(new java.awt.Color(204, 204, 204));
        tf_doisDaltura1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_doisDaltura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_doisDaltura1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_doisDaltura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 670, 90, -1));

        tf_colunaDescricao.setBackground(new java.awt.Color(204, 204, 204));
        tf_colunaDescricao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_colunaDescricao.setBorder(null);
        getContentPane().add(tf_colunaDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 100, 30));

        tf_alturadescricao.setBackground(new java.awt.Color(204, 204, 204));
        tf_alturadescricao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_alturadescricao.setBorder(null);
        getContentPane().add(tf_alturadescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 90, 30));

        tf_LarguraDescricao.setBackground(new java.awt.Color(204, 204, 204));
        tf_LarguraDescricao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_LarguraDescricao.setBorder(null);
        getContentPane().add(tf_LarguraDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 110, 30));

        tf_TamanhoDescricao.setBackground(new java.awt.Color(204, 204, 204));
        tf_TamanhoDescricao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_TamanhoDescricao.setBorder(null);
        getContentPane().add(tf_TamanhoDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, 120, 30));

        TF_text2.setBorder(null);
        getContentPane().add(TF_text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 315, 660, 25));

        TF_text3.setBorder(null);
        getContentPane().add(TF_text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 660, 25));

        TF_text4.setBorder(null);
        getContentPane().add(TF_text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 660, 25));

        TF_text5.setBorder(null);
        getContentPane().add(TF_text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 505, 660, 25));

        TF_text6.setBorder(null);
        TF_text6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_text6ActionPerformed(evt);
            }
        });
        getContentPane().add(TF_text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 660, 25));

        tf_colunaText2.setBackground(new java.awt.Color(204, 204, 204));
        tf_colunaText2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_colunaText2.setBorder(null);
        tf_colunaText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_colunaText2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_colunaText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 60, 30));

        tf_colunaText3.setBackground(new java.awt.Color(204, 204, 204));
        tf_colunaText3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_colunaText3.setBorder(null);
        tf_colunaText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_colunaText3ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_colunaText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 60, 30));

        tf_colunaText4.setBackground(new java.awt.Color(204, 204, 204));
        tf_colunaText4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_colunaText4.setBorder(null);
        tf_colunaText4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_colunaText4ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_colunaText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 60, 30));

        tf_colunaText5.setBackground(new java.awt.Color(204, 204, 204));
        tf_colunaText5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_colunaText5.setBorder(null);
        tf_colunaText5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_colunaText5ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_colunaText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 60, 30));

        tf_colunaText6.setBackground(new java.awt.Color(204, 204, 204));
        tf_colunaText6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_colunaText6.setBorder(null);
        tf_colunaText6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_colunaText6ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_colunaText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 60, 30));

        tf_alturaText2.setBackground(new java.awt.Color(204, 204, 204));
        tf_alturaText2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_alturaText2.setBorder(null);
        tf_alturaText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_alturaText2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_alturaText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 60, 30));

        tf_alturaText3.setBackground(new java.awt.Color(204, 204, 204));
        tf_alturaText3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_alturaText3.setBorder(null);
        tf_alturaText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_alturaText3ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_alturaText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 60, 30));

        tf_alturaText4.setBackground(new java.awt.Color(204, 204, 204));
        tf_alturaText4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_alturaText4.setBorder(null);
        tf_alturaText4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_alturaText4ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_alturaText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 60, 30));

        tf_alturaText5.setBackground(new java.awt.Color(204, 204, 204));
        tf_alturaText5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_alturaText5.setBorder(null);
        tf_alturaText5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_alturaText5ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_alturaText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 60, 30));

        tf_alturaText6.setBackground(new java.awt.Color(204, 204, 204));
        tf_alturaText6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_alturaText6.setBorder(null);
        tf_alturaText6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_alturaText6ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_alturaText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 60, 30));

        jLabel1.setText("Coluna");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel3.setText("Largura");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 240, -1, -1));

        jLabel4.setText("Altura");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabel5.setText("Altura");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        jLabel6.setText("Altura");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        jLabel7.setText("Altura");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        tf_LarguraText1.setBackground(new java.awt.Color(204, 204, 204));
        tf_LarguraText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_LarguraText1.setBorder(null);
        getContentPane().add(tf_LarguraText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 260, 60, 30));

        jLabel8.setText("Altura");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel9.setText("Altura");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, -1));

        tf_LarguraText2.setBackground(new java.awt.Color(204, 204, 204));
        tf_LarguraText2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_LarguraText2.setBorder(null);
        getContentPane().add(tf_LarguraText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 310, 60, 30));

        tf_LarguraText3.setBackground(new java.awt.Color(204, 204, 204));
        tf_LarguraText3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_LarguraText3.setBorder(null);
        getContentPane().add(tf_LarguraText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 370, 60, 30));

        tf_LarguraText4.setBackground(new java.awt.Color(204, 204, 204));
        tf_LarguraText4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_LarguraText4.setBorder(null);
        getContentPane().add(tf_LarguraText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 440, 60, 30));

        tf_LarguraText5.setBackground(new java.awt.Color(204, 204, 204));
        tf_LarguraText5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_LarguraText5.setBorder(null);
        getContentPane().add(tf_LarguraText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 500, 60, 30));

        tf_LarguraText6.setBackground(new java.awt.Color(204, 204, 204));
        tf_LarguraText6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_LarguraText6.setBorder(null);
        getContentPane().add(tf_LarguraText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 560, 60, 30));

        jLabel10.setText("Largura");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 350, -1, -1));

        jLabel11.setText("Largura");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 420, -1, -1));

        jLabel12.setText("Largura");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 480, -1, -1));

        jLabel13.setText("Largura");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 540, -1, -1));

        jLabel14.setText("Largura");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 290, -1, -1));

        jLabel15.setText("Coluna");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel16.setText("Coluna");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jLabel17.setText("Coluna");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        jLabel18.setText("Coluna");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        jLabel19.setText("Tamanho");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 290, -1, -1));

        jLabel20.setText("Coluna");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        tf_TamanhoText2.setBackground(new java.awt.Color(204, 204, 204));
        tf_TamanhoText2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_TamanhoText2.setBorder(null);
        getContentPane().add(tf_TamanhoText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, 60, 30));

        tf_TamanhoText3.setBackground(new java.awt.Color(204, 204, 204));
        tf_TamanhoText3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_TamanhoText3.setBorder(null);
        getContentPane().add(tf_TamanhoText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 370, 60, 30));

        tf_TamanhoText4.setBackground(new java.awt.Color(204, 204, 204));
        tf_TamanhoText4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_TamanhoText4.setBorder(null);
        getContentPane().add(tf_TamanhoText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, 60, 30));

        tf_TamanhoText5.setBackground(new java.awt.Color(204, 204, 204));
        tf_TamanhoText5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_TamanhoText5.setBorder(null);
        getContentPane().add(tf_TamanhoText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 500, 60, 30));

        tf_TamanhoText6.setBackground(new java.awt.Color(204, 204, 204));
        tf_TamanhoText6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_TamanhoText6.setBorder(null);
        getContentPane().add(tf_TamanhoText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 560, 60, 30));

        jLabel21.setText("Tamanho");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 350, -1, -1));

        jLabel22.setText("Tamanho");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 420, -1, -1));

        jLabel23.setText("Tamanho");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, -1, -1));

        jLabel24.setText("Tamanho");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, -1, -1));

        jLabel25.setText("Tamanho");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, -1, -1));

        jLabel26.setText("Alinhamemento esquerdo");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel27.setText("Espaçameto das linhas");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel28.setText("Coluna logo");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jLabel29.setText("Altura Logo");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        jLabel30.setText("Largura descrição");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, -1, -1));

        jLabel31.setText("Altura descrição");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 80, -1));

        jLabel32.setText("Tamanho descrição");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, -1));

        jLabel33.setText("Coluna Descricao");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, -1, -1));

        jLabel34.setText("Col2D 2");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, -1, -1));

        jLabel35.setText("Col2D 1");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, -1, -1));

        jLabel36.setText("Altura 2D 2");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 750, -1, -1));

        jLabel37.setText("Altura 2D 1");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, -1, -1));

        jLabel38.setText("Coluna MADE IN");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 670, -1, -1));

        jLabel39.setText("Coluna BRAZIL");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 720, -1, -1));

        tf_LarguraMadeIn.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(tf_LarguraMadeIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 660, 80, -1));

        tf_LaguraBrasil.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(tf_LaguraBrasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 810, 70, -1));

        jLabel40.setText("Largura MADE IN");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 640, -1, -1));

        jLabel41.setText("Largura BRASIL");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 790, -1, -1));

        tf_TamMadeIn.setBackground(new java.awt.Color(204, 204, 204));
        tf_TamMadeIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tf_TamMadeIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 700, 80, -1));

        tf_TamBrasil.setBackground(new java.awt.Color(204, 204, 204));
        tf_TamBrasil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tf_TamBrasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 750, 80, -1));

        jLabel42.setText("Tamanho MADE");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 680, -1, -1));

        jLabel43.setText("Tamanho BRASIL");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 730, -1, -1));

        tf_codigoBarrasColuna.setBackground(new java.awt.Color(204, 204, 204));
        tf_codigoBarrasColuna.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tf_codigoBarrasColuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 780, 100, -1));

        tf_codigoBarrasAltura.setBackground(new java.awt.Color(204, 204, 204));
        tf_codigoBarrasAltura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tf_codigoBarrasAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 670, 90, -1));

        jLabel44.setText("Coluna código de barras");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 760, -1, -1));

        jLabel45.setText("Altura código de barras");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 650, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 220, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Config/MARCARA.JPG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1160, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_alturaText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_alturaText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_alturaText1ActionPerformed

    private void tf_doisDColuna1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_doisDColuna1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_doisDColuna1ActionPerformed

    private void tf_doisDaltura2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_doisDaltura2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_doisDaltura2ActionPerformed

    private void tf_colunaBrazilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_colunaBrazilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_colunaBrazilActionPerformed

    private void tf_doisDaltura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_doisDaltura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_doisDaltura1ActionPerformed

    private void tf_colunaText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_colunaText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_colunaText1ActionPerformed

    private void TF_text6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_text6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_text6ActionPerformed

    private void TF_text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_text1ActionPerformed

    private void tf_colunaText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_colunaText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_colunaText2ActionPerformed

    private void tf_colunaText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_colunaText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_colunaText3ActionPerformed

    private void tf_colunaText4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_colunaText4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_colunaText4ActionPerformed

    private void tf_colunaText5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_colunaText5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_colunaText5ActionPerformed

    private void tf_colunaText6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_colunaText6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_colunaText6ActionPerformed

    private void tf_alturaText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_alturaText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_alturaText2ActionPerformed

    private void tf_alturaText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_alturaText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_alturaText3ActionPerformed

    private void tf_alturaText4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_alturaText4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_alturaText4ActionPerformed

    private void tf_alturaText5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_alturaText5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_alturaText5ActionPerformed

    private void tf_alturaText6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_alturaText6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_alturaText6ActionPerformed

    private void tf_colunaMadeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_colunaMadeInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_colunaMadeInActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          mar.buscar("rev7");
          tf_espacamentoEsquerdo.setText(mar.getAlinhamenedoEsq());
          tf_espacamentoLinha.setText(mar.getEspacamentoLinha());
          tf_colunaLogo.setText(mar.getColunaLogo());
          tf_AlturaLogo.setText(mar.getAlturaLogo());
          tf_TamanhoDescricao.setText(mar.getTamanhoDescricao());
          tf_colunaDescricao.setText(mar.getColunaDescricao());        
          tf_LarguraDescricao.setText(mar.getLarguraDescricao());
          tf_alturadescricao.setText(mar.getAlturadescricao()); 
          TF_text1.setText(mar.getText1()); 
          tf_colunaText1.setText(mar.getColunaText1()); 
          tf_LarguraText1.setText(mar.getLarguraText1());  
          tf_alturaText1.setText(mar.getAlturaText1());  
          tf_TamanhoText1.setText(mar.getTamanhoText1());    
          
           TF_text2.setText(mar.getText2()); 
          tf_colunaText2.setText(mar.getColunaText2()); 
          tf_LarguraText2.setText(mar.getLarguraText2());  
          tf_alturaText2.setText(mar.getAlturaText2());  
          tf_TamanhoText2.setText(mar.getTamanhoText2());
        
          TF_text3.setText(mar.getText3()); 
          tf_colunaText3.setText(mar.getColunaText3()); 
          tf_LarguraText3.setText(mar.getLarguraText3());  
          tf_alturaText3.setText(mar.getAlturaText3());  
          tf_TamanhoText3.setText(mar.getTamanhoText3());
           TF_text4.setText(mar.getText4()); 
          tf_colunaText4.setText(mar.getColunaText4()); 
          tf_LarguraText4.setText(mar.getLarguraText4());  
          tf_alturaText4.setText(mar.getAlturaText4());  
          tf_TamanhoText4.setText(mar.getTamanhoText4());    
           TF_text5.setText(mar.getText5()); 
          tf_colunaText5.setText(mar.getColunaText5()); 
          tf_LarguraText5.setText(mar.getLarguraText5());  
          tf_alturaText5.setText(mar.getAlturaText5());  
          tf_TamanhoText5.setText(mar.getTamanhoText5());    
           TF_text6.setText(mar.getText6()); 
          tf_colunaText6.setText(mar.getColunaText6()); 
          tf_LarguraText6.setText(mar.getLarguraText6());  
          tf_alturaText6.setText(mar.getAlturaText6());  
          tf_TamanhoText6.setText(mar.getTamanhoText6());    
          
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_text1;
    private javax.swing.JTextField TF_text2;
    private javax.swing.JTextField TF_text3;
    private javax.swing.JTextField TF_text4;
    private javax.swing.JTextField TF_text5;
    private javax.swing.JTextField TF_text6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField tf_AlturaLogo;
    private javax.swing.JTextField tf_LaguraBrasil;
    private javax.swing.JTextField tf_LarguraDescricao;
    private javax.swing.JTextField tf_LarguraMadeIn;
    private javax.swing.JTextField tf_LarguraText1;
    private javax.swing.JTextField tf_LarguraText2;
    private javax.swing.JTextField tf_LarguraText3;
    private javax.swing.JTextField tf_LarguraText4;
    private javax.swing.JTextField tf_LarguraText5;
    private javax.swing.JTextField tf_LarguraText6;
    private javax.swing.JTextField tf_TamBrasil;
    private javax.swing.JTextField tf_TamMadeIn;
    private javax.swing.JTextField tf_TamanhoDescricao;
    private javax.swing.JTextField tf_TamanhoText1;
    private javax.swing.JTextField tf_TamanhoText2;
    private javax.swing.JTextField tf_TamanhoText3;
    private javax.swing.JTextField tf_TamanhoText4;
    private javax.swing.JTextField tf_TamanhoText5;
    private javax.swing.JTextField tf_TamanhoText6;
    private javax.swing.JTextField tf_alturaText1;
    private javax.swing.JTextField tf_alturaText2;
    private javax.swing.JTextField tf_alturaText3;
    private javax.swing.JTextField tf_alturaText4;
    private javax.swing.JTextField tf_alturaText5;
    private javax.swing.JTextField tf_alturaText6;
    private javax.swing.JTextField tf_alturadescricao;
    private javax.swing.JTextField tf_codigoBarrasAltura;
    private javax.swing.JTextField tf_codigoBarrasColuna;
    private javax.swing.JTextField tf_colunaBrazil;
    private javax.swing.JTextField tf_colunaDescricao;
    private javax.swing.JTextField tf_colunaLogo;
    private javax.swing.JTextField tf_colunaMadeIn;
    private javax.swing.JTextField tf_colunaText1;
    private javax.swing.JTextField tf_colunaText2;
    private javax.swing.JTextField tf_colunaText3;
    private javax.swing.JTextField tf_colunaText4;
    private javax.swing.JTextField tf_colunaText5;
    private javax.swing.JTextField tf_colunaText6;
    private javax.swing.JTextField tf_doisDColuna1;
    private javax.swing.JTextField tf_doisDColuna2;
    private javax.swing.JTextField tf_doisDaltura1;
    private javax.swing.JTextField tf_doisDaltura2;
    private javax.swing.JTextField tf_espacamentoEsquerdo;
    private javax.swing.JTextField tf_espacamentoLinha;
    // End of variables declaration//GEN-END:variables

    

}
